### ISSUE TITLE
React Warning: "React does not recognize the `targetRef` prop on a DOM element."

### ISSUE THREAD

**Issue by joecarver** [maslianok/react-resize-detector#113]
This error displays in the browser console when using `react-resize-detector` with children that are class or functional components.

I believe the error is because the `targetRef` property is only removed from elements in certain cases, i.e. when the child is a native DOM element, but not when the element is a component.

**Comment by joecarver** [comment]
On further inspection, I noticed that `targetRef` doesn't actually have to be passed to the child component in any case, so my PR just removed it from `childProps` inside `render()`.

**Comment by maslianok** [comment]
Hey @joecarver,
Thanks for your investigation and pull request!

I don't think we can simply remove `targetRef` from the child component. Maybe it will solve your problem but it may add other bugs (for example, in HOC approach we use that ref).

Today I published a new major release (v6.0.0-alpha.1). Can you please update and check if the bug still persist? There is a small chance that it's gone with other improvements.

Otherwise please provide a code-snippet that reproduces the above problem.

Thanks in advance!

**Comment by joecarver** [comment]
Hi @maslianok, thanks for the reply! That's OK, I figured that would probably be the case. We are using a forked version with my change.

I just tried with the new version and unfortunately the problem still persists. I will try find time to put together a reproduction soon, but as I said we are using a fork so we're OK for the time being. 

Thank you anyway for the very nice library!

**Comment by maslianok** [comment]
Thank you 🙌

I'm going to close this issue.
If, at some point, you will decide to discuss the problem - let me know

**Comment by Scong** [comment]
For those of you who run into this issue, I believe this happens when ReactResizeDetector has react children and you set a targetRef.

ReactResizeDetector should have no children or follow the Child Function Pattern probably

https://github.com/maslianok/react-resize-detector#3-child-function-pattern
